name: 'Ad | voca | Te | ch'
favicon: null
layout_spectrum: 0.5497001309413463
typography_spectrum: 0.724606900010258
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6615551339928061
  lightness: 0.610155449481681
  saturation: 0.513850188581273
  rhythmicContrast: 0.563359014922753
purpose: []
